source 'https://rubygems.org'

gem 'rake'

gem 'rails'
gem 'railties'

gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'bootstrap-sass', '~> 3.2.0'
gem "bootstrap-switch-rails"
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jquery-turbolinks'
gem 'turbolinks'

gem 'jbuilder'
gem 'sqlite3'
gem 'web-console', '~> 2.0'
gem 'spring'
gem 'better_errors'
gem 'quiet_assets'
gem 'rails_layout'
