views:
  header_view:
    elements:
      home_button:
        xpath: '//a[text()="Home"]'
        click:
          after:
            change_screen: 'home_screen'
      contact_button:
        xpath: '//a[text()="Contacts"]'
        click:
          after:
            change_screen: 'contact_screen'