views:
  header_view:
    elements:
      home_button:
        xpath: '//a[text()="Home"]'
        click:
          after:
            change_screen: 'home_screen'
      about_button:
        xpath: '//a[text()="About"]'
        click:
          after:
            change_screen: 'about_screen'
      contact_button:
        xpath: '//a[text()="Contact"]'
        click:
          after:
            change_screen: 'contact_screen'