source 'https://rubygems.org'

gem 'rake'

gem 'rails'
gem 'railties'

gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'bootstrap-sass', '~> 3.2.0'
gem "bootstrap-switch-rails"
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jquery-turbolinks'
gem 'turbolinks'

gem 'jbuilder'

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end


group :development do
  gem 'better_errors'
  gem 'quiet_assets'
  gem 'rails_layout'
end

group :development, :test do
  gem 'sqlite3'
end

group :production do
  gem 'pg'
  gem 'rails_12factor'
end
